/**
 * MIT License
 *
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>


namespace facebook {
namespace react {
class NativeMMKVEventEmitter : public ViewEventEmitter {
public:
    using ViewEventEmitter::ViewEventEmitter;

    struct OnSubjectAreaChanged {
        Float latitude;
        Float longitude;
    };

    struct OnGoogleVisionBarcodesDetected {
        Float overlook;
    };

    struct OnCameraReady {};

    struct OnRecordingStartNativeEvent {
        std::string uri;
        int videoOrientation;
        int deviceOrientation;
    };

    struct OnRecordingStart {
        OnRecordingStartNativeEvent nativeEvent;
    };

    struct OnStopRecording {};

    struct OnAudioInterrupted {};

    struct OnAudioConnected {};

    struct OnPictureSaved {};

    struct OnFaceDetected {
        Float latitude;
        Float longitude;
    };

    struct OnTouch {
        Float x;
        Float y;
    };

    struct TapCallback {
        bool isDoubleTap;
        OnTouch touchOrigin;
    };

    struct OnMountError {
        std::string message;
    };

    struct OnBarCodeReadBoundsOrigin {
        std::string x;
        std::string y;
    };

    struct OnBarCodeReadBoundsSize {
        std::string width;
        std::string height;
    };

    struct OnBarCodeReadBounds {
        OnBarCodeReadBoundsOrigin origin;
        OnBarCodeReadBoundsSize size;
    };

    struct OnBarCodeRead {
        std::string data;
        std::string rawData;
        std::string type;
        OnBarCodeReadBounds bounds;
        std::string image;
    };
    
//    enum class OnStatusChangeCameraStatus { Ready, Pending_authorization, Not_authorized };
//
//    static char const *toString(const OnStatusChangeCameraStatus value) {
//        switch (value) {
//        case OnStatusChangeCameraStatus::Ready:
//            return "ready";
//        case OnStatusChangeCameraStatus::Pending_authorization:
//            return "pending_authorization";
//        case OnStatusChangeCameraStatus::Not_authorized:
//            return "not_authorized";
//        }
//    }
//
//    enum class OnStatusChangeRecordAudioPermissionStatus { Ready, Pending_authorization, Not_authorized };
//
//    static char const *toString(const OnStatusChangeRecordAudioPermissionStatus value) {
//        switch (value) {
//        case OnStatusChangeRecordAudioPermissionStatus::Ready:
//            return "ready";
//        case OnStatusChangeRecordAudioPermissionStatus::Pending_authorization:
//            return "pending_authorization";
//        case OnStatusChangeRecordAudioPermissionStatus::Not_authorized:
//            return "not_authorized";
//        }
//    }

    struct OnStatusChange {
        std::string cameraStatus;
        std::string recordAudioPermissionStatus;
    };


    struct OnMapPoiClick {};

    struct OnTaskPhoto {};

    struct OnPictureTaken {};

    void onBarCodeRead(OnBarCodeRead value) const;

    void onSubjectAreaChanged(OnSubjectAreaChanged value) const;

    void onGoogleVisionBarcodesDetected(OnGoogleVisionBarcodesDetected value) const;

    void onCameraReady(OnCameraReady value) const;
    void onRecordingStart(OnRecordingStart value) const;
    void onRecordingEnd(OnStopRecording value) const;

    void onAudioInterrupted(OnAudioInterrupted value) const;

    void onAudioConnected(OnAudioConnected value) const;

    void onPictureSaved(OnPictureSaved value) const;

    void onFaceDetected(OnFaceDetected value) const;

    void onTouch(TapCallback value) const;

    void onMountError(OnMountError value) const;

    void onTaskPhoto(OnTaskPhoto value) const;

    void onPictureTaken(OnPictureTaken value) const;

    void onStatusChange(OnStatusChange value) const;
};
} // namespace react
} // namespace facebook
